/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bolton.boltonlinker;

import com.bolton.boltonlinker.view.Login;

public class App {

    public static void main(String[] args) {
        Login login = new Login();
        login.setVisible(true);
    }
}
